config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
  controllers: { registrations: 'registrations' }
  root 'posts#index'

  get '/users/:id', to: 'users#show', as: 'user'

  resources :posts, only: %i(index new create show destroy edit update) do
    resources :photos, only: %i(create)
    resources :likes, only: %i(create destroy)
    resources :comments, only: %i(create destroy)
    resources :pages, only: %i(create destroy show edit update)
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :post

  validates :user_id, uniqueness: { scope: :post_id }
end

app/models/page.rb
class Page < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/photo.rb
class Photo < ApplicationRecord
  belongs_to :post

  # validates :image, presence: true
  mount_uploader :image, ImageUploader
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :photos, dependent: :destroy
  has_many :likes, -> { order(created_at: :desc) }, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :pages, dependent: :destroy

  accepts_nested_attributes_for :photos

  def liked_by(user)
    # user_idとpost_idが一致するlikeを検索する
    Like.find_by(user_id: user.id, post_id: id)
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :likes
  has_many :posts, dependent: :destroy
  has_many :comments
  has_many :pages
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, presence: true, length: { maximum: 50 }

  def update_without_current_password(params, *options)
    params.delete(:current_password)

    if params[:password].blank? && params[:password_confirmation].blank?
      params.delete(:password)
      params.delete(:password_confirmation)
    end

    result = update_attributes(params, *options)
    clean_up_passwords
    result
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
      devise_parameter_sanitizer.permit(:account_update, keys: [:name])
    end
    
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!

  def create
    @comment = Comment.new(comment_params)
    @post = @comment.post
    if @comment.save
      respond_to :js
    else
      flash[:alert] = "コメントに失敗しました"
    end
  end

  def destroy
    @comment = Comment.find_by(id: params[:id])
    @post = @comment.post
    if @comment.destroy
      respond_to :js
    else
      flash[:alert] = "コメントの削除に失敗しました"
    end
  end

  private
    def comment_params
      params.required(:comment).permit(:user_id, :post_id, :comment)
    end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :authenticate_user!

  def create
    @like = current_user.likes.build(like_params)
    @post = @like.post
    if @like.save
      respond_to :js
    end
  end

  def destroy
    @like = Like.find_by(id: params[:id])
    @post = @like.post
    if @like.destroy
      respond_to :js
    end
  end

  private
    def like_params
      params.permit(:post_id)
    end
    
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  # def home
  # end
  before_action :authenticate_user!
  before_action :set_page, only: %i(show destroy edit update)

  def create
    @page = Page.new(page_params)
    @post = @page.post
    if @page.save
      respond_to :js
    else
      flash[:alert] = "投稿に失敗しました"
    end
  end

  def destroy
    # @page = Page.find_by(id: params[:id])
    @post = @page.post
    if @page.destroy
      respond_to :js
    else
      flash[:alert] = "投稿の削除に失敗しました"
    end
  end

  def show
  end

  def edit
    # @pages = @post.pages.includes(:user)
  end
  
  def update
    @page.update(page_params)
    redirect_to '/'
  end

  private
    def page_params
      params.required(:page).permit(:user_id, :post_id, :body, :page)
    end

    def set_page
      @page = Page.find_by(id: params[:id])
    end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_post, only: %i(show destroy edit update)

  def new
    @post = Post.new
    @post.photos.build
  end

  # def create
  #   @post = Post.new(post_params)
  #   if @post.photos.present?
  #     @post.save
  #     redirect_to root_path
  #     flash[:notice] = "投稿が保存されました"
  #   else
  #     redirect_to root_path
  #     flash[:alert] = "投稿に失敗しました"
  #   end
  # end

  def create
    @post = Post.new(post_params)
    @post.save
    redirect_to root_path
    flash[:notice] = "投稿が保存されました"
  end

  def index
    @posts = Post.limit(10).includes(:photos, :user).order('created_at DESC')
  end

  def show
  end

  def destroy
    if @post.user == current_user
      flash[:notice] = "投稿が削除されました" if @post.destroy
    else
      flash[:alert] = "投稿の削除に失敗しました"
    end
    redirect_to root_path
  end

  def edit
    @pages = @post.pages.includes(:user)
  end

  def update
    @post.update(post_params)
    redirect_to '/'
  end

  private
  def post_params
    params.require(:post).permit(:caption, photos_attributes: [:image]).merge(user_id: current_user.id)
  end

  def set_post
    @post = Post.find_by(id: params[:id])
  end

end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  protected

  def update_resource(resource, params)
    resource.update_without_current_password(params)
  end

  def after_update_path_for(resource)
    user_path(resource)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find_by(id: params[:id])
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper

  def avatar_url(user)
    return user.profile_photo unless user.profile_photo.nil?
    gravatar_id = Digest::MD5::hexdigest(user.email).downcase
    "https://www.gravatar.com/avatar/#{gravatar_id}.jpg"
  end
  
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/likes/create.js.haml
$('#like-icon-post-#{@post.id.to_s}').
html('#{link_to "いいね", post_like_path(@post.id, @like), method: :DELETE, remote: true, class: "loved hide-text"}');
$('#like-text-post-#{@post.id.to_s}').
html('#{j render "posts/like_text", { likes: @post.likes }}');

app/views/pages/_page_list.html.erb
<% post.pages.each do |page| %>
  <div class="mb-2">
    <% if page.user == current_user %>
      <%= link_to "", post_page_path(post.id, page), method: :delete, remote: true, class: "delete-comment" %>
    <% end %>
    <span>
      <strong>
        <%= link_to page.user.name, user_path(page.user), class: "no-text-decoration black-color" %>
      </strong>
    </span>
    <%# <span><%= comment.comment</span> %>
    <%# <%= link_to post_pages_path(post.id, page), class: "no-text-decoration" do %>
    <%= link_to "/posts/#{post.id}/pages/#{page.id}" do %>
      <span><%= page.body %></span>
    <% end %>
  </div>
<% end %>

app/views/pages/show.html.erb
<div class="col-md-10 col-md-offset-1 mx-auto postShow-wrap">
  <div class="row post-wrap">
    <div class="col-md-8">
      <div class="card-left">
        <%# <%= image_tag @post.photos.first.image.url(:medium), class: "card-img-top" %> 
      </div>
    </div>
    <div class="col-md-4">
      <div class="card-right">
        <div class="card-right-comment">
          <%= link_to edit_post_page_path do %>
            <span><%= @page.body %></span>
          <% end %>
          <div class="card-right-name">
            <%= link_to user_path(@page.user), class: "no-text-decoration" do %>
              <%= image_tag avatar_url(@page.user), class: "post-profile-icon" %>
            <% end %>
            <%= link_to user_path(@page.user), class: "black-color no-text-decoration post-user-name",
              title: @page.user.name do %>
              <strong><%= @page.user.name %></strong>
            <% end %>
            <% if @page.user_id == current_user.id %>
              <%# <%= link_to page_path(@page), method: :delete, class: "ml-auto mx-0 my-auto" do %>
                <%# <div class="delete-post-icon">
                </div> %>
              <%# <% end %>
              <%# <%= link_to(edit_page_path(@page)) do %>
                <%# 編集 %>
              <%# <% end %>
            <% end %>
          </div>
          <div class="m-2">
            <strong>
              <%= @page.body %>
            </strong>
          </div>
          <div class="comment-post-id">
            <div class="m-2">

              <%# <div id="comment-post-<%= @post.id.to_s %>
                <%# <%= render 'comment_list', post: @post %>
              <%# </div> %>


            <%# </div>
            <div class="m-2">
              <div id="page-post-<%= @post.id.to_s %>
                <%# <%= render 'page_list', post: @post %>
              <%# </div> %>
            <%# </div> %>
          </div>
        </div>
        <div class="row parts">

          <%# <div id="like-icon-post-<%= @post.id.to_s %>
            <%# <% if @post.liked_by(current_user).present? %>
              <%# <%= link_to "いいねを取り消す", post_like_path(@post.id, @post.liked_by(current_user)), method: :DELETE, remote: true, class: "loved hide-text" %>
            <%# <% else %>
              <%# <%= link_to "いいね", post_likes_path(@post), method: :POST, remote: true, class: "love hide-text" %>
            <%# <% end %>
          <%# </div> %>
        </div>

        <%# <div id="like-text-post-<%= @post.id.to_s %>
          <%# <%= render "like_text", { likes: @post.likes } %> 
        <%# </div> %> 

        <%# <div class="post-time"><%= time_ago_in_words(@post.created_at).upcase前</div> %>
        <%# <hr> %>
          <%# <div class="row parts" id="comment-form-post-<%= @post.id.to_s %>
          <%# <%= form_with model: [@post, Comment.new],  class: "w-100" do |f| %> 
            <%# <%= f.hidden_field :user_id, value: current_user.id %>
            <%# <%= f.hidden_field :post_id, value: @post.id %>
            <%# <%= f.text_field :comment, class: "form-control comment-input border-0", placeholder: "コメント ...", autocomplete: :off %>
          <%# <% end %>
        <%# </div> %>

        <%# <div class="row parts" id="page-form-post-<%= @post.id.to_s %>
          <%# <%= form_with model: [@post, Page.new],  class: "w-100" do |f| %>
            <%# <%= f.hidden_field :user_id, value: current_user.id %>
            <%# <%= f.hidden_field :post_id, value: @post.id %>
            <%# <%= f.text_field :body, class: "form-control comment-input border-0", placeholder: "投稿 ...", autocomplete: :off %>
          <%# <% end %>
        <%# </div> %>

      </div>
    </div>
  </div>
</div>

app/views/pages/show.html.haml
.col-md-10.col-md-offset-1.mx-auto.postShow-wrap
  .row.post-wrap
    -# .col-md-0
    -#   .card-left
    .col-md-10.center
      .card-right
        -# ここは作者用メニューです
      .card-body
        -# 新しい話を追加する
        -# .row.parts{:id => "page-form-post-#{@post.id.to_s}"}
        -#   = form_with model:[@post, Page.new], class: "upload-images p-0 border-0" do |f|
        -#     = f.hidden_field :user_id, value: current_user.id
        -#     = f.hidden_field :post_id, value: @post.id
        -#     = f.text_field :title  ,class: "form-control", placeholder: "タイトル", autocomplete: :on
        -#     = f.text_area :body, placeholder: "本文" , rows: "10", class: "form-control", autocomplete: :on

        -#     = f.submit "投稿する", class: "btn btn-primary"
        -#     %hr
        .card-right-comment
          .card-right__first
            = link_to user_path(@page.user), class: "no-text-decoration" do
              -# = image_tag avatar_url(@post.user), class: "post-profile-icon"
            %strong.postShowTitle
              = @page.title
          .card-right__second
            = link_to user_path(@page.user), class: "black-color no-text-decoration post-user-name", title: @page.user.name do
              作者: 
              %strong= @page.user.name
          -#   - if @post.user_id == current_user.id
          -#     = link_to post_path(@post), method: :delete, class: "ml-auto mx-0 my-auto" do
          -#       .delete-post-icon
          -#     = link_to(edit_post_path(@post)) do
          -#       編集
          -# .m-2
          %br
            %p.caption= safe_join(@page.body.split("\n"), tag(:br))
            -# %div{:id => "page-post-#{@page.id.to_s}"}
            -#   = render 'page_list', post: @post
        .row.parts
          = link_to edit_post_page_path do
            編集
        -#   %div{:id => "like-icon-post-#{@post.id.to_s}"}
        -#     - if @post.liked_by(current_user).present?
        -#       = link_to "いいねを取り消す", post_like_path(@post.id, @post.liked_by(current_user)), method: :DELETE, remote: true, class: "loved hide-text"
        -#     - else
        -#       = link_to "いいね", post_likes_path(@post), method: :POST, remote: true, class: "love hide-text"
        -# %div{:id => "like-text-post-#{@post.id.to_s}"}
        -#   = render "like_text", { likes: @post.likes }
        -# .post-time
        -#   = time_ago_in_words(@post.created_at).upcase
        -#   前
        -# %hr/
        -# .row.parts{:id => "comment-form-post-#{@post.id.to_s}"}
        -#   = form_with model: [@post, Comment.new],  class: "w-100" do |f|
        -#     = f.hidden_field :user_id, value: current_user.id
        -#     = f.hidden_field :post_id, value: @post.id
        -#     = f.text_field :comment, class: "form-control comment-input border-0", placeholder: "コメント ...", autocomplete: :off
        -#   .comment-post-id
        -#     .m-2
        -#       %div{:id => "comment-post-#{@post.id.to_s}"}
        -#         = render 'comment_list', post: @post


-# .col-md-10.col-md-offset-1.mx-auto.postShow-wrap
-#   .row.post-wrap
-#     .col-md-8
-#       .card-left
-#     .col-md-4
-#       .card-right
-#         .card-right-comment
-#           = link_to edit_post_page_path do
-#             %span= @page.body
-#           .card-right-name
-#             = link_to user_path(@page.user), class: "no-text-decoration" do
-#               = image_tag avatar_url(@page.user), class: "post-profile-icon"
-#             = link_to user_path(@page.user), class: "black-color no-text-decoration post-user-name", |
-#               title: @page.user.name do                                                              |
-#               %strong= @page.user.name
-#           - if @page.user_id == current_user.id
-#             .m-2
-#               %strong
-#                 = @page.body
-#             .comment-post-id
-#               .m-2
-#             .row.parts

app/views/partial/_secondLine.html.haml
.second-line
  %ul.second-line__info
    %li.second-line__info--box
      %i.fas.fa-home
        - if user_signed_in?
          = link_to "マイページ", "/users/#{current_user.id}",class: "second-line__bt"
        -# - else
        -#   = link_to "マイページ", new_user_session_path ,class: "second-line__bt"
      -# %li.second-line__info--box
        -# %i.fas.fa-sign-out-alt
        -#   - if user_signed_in?
        -#     = link_to "ログアウト", destroy_user_session_path, method: :delete, class: "second-line__bt"
          -# - else
          -#   = link_to "ログイン", new_user_session_path, class: "second-line__bt"
      %li.second-line__info--box
        %i.fas.fa-book-reader
          = link_to  "小説", posts_path, class: "second-line__bt"
      %li.second-line__info--box
        %i.fas.fa-user-edit
          = link_to "投稿", new_post_path, class: "second-line__bt"
          -# = link_to  "活動報告", tweets_path, class: "second-line__bt"
      -# %li.second-line__info--box

      -# .second-line__first
        
      -# .second-line__second
      -# = link_to "新規登録", new_user_registration_path, class: 'post'
        

app/views/posts/index.html.erb
<% @posts.each do |post| %>
  <div class="col-md-8 col-md-2 mx-auto">
    <div class="card-wrap">
      <div class="card">
        <div class="card-header align-items-center d-flex">
          <%= link_to user_path(post.user), class: "no-text-decoration" do %>
            <%= image_tag avatar_url(post.user), class: "post-profile-icon" %>
          <% end %>
          <%= link_to user_path(post.user), class: "black-color no-text-decoration",
            title: post.user.name do %>
            <strong><%= post.user.name %></strong>
          <% end %>

          <% if post.user_id == current_user.id %>
            <%= link_to post_path(post), method: :delete, class: "ml-auto mx-0 my-auto" do %>
              <div class="delete-post-icon">
              </div>
            <% end %>
          <% end %>
            <%= link_to(edit_post_path(post)) do %>
              編集
            <% end %>
        </div>

        <%# <%= link_to(post_path(post)) do %>
          <%# <%= image_tag post.photos.first.image.url(:medium), class: "card-img-top" %>
        <%# <% end %> 

        <div class="card-body">
          <div class="row parts">

            <div id="like-icon-post-<%= post.id.to_s %>">
              <% if post.liked_by(current_user).present? %>
                <%= link_to "いいねを取り消す", post_like_path(post.id, post.liked_by(current_user)), method: :DELETE, remote: true, class: "loved hide-text" %>
              <% else %>
                <%= link_to "いいね", post_likes_path(post), method: :POST, remote: true, class: "love hide-text" %>
              <% end %>
            </div>

            <%= link_to "", "#", class: "comment" %>
          </div>

          <div id="like-text-post-<%= post.id.to_s %>">
            <%= render "like_text", { likes: post.likes } %>
          </div>

          <div>
            <span><strong><%= post.user.name %></strong></span>
            <span><%= post.caption %></span>
            <%= link_to time_ago_in_words(post.created_at).upcase + "前", post_path(post), class: "post-time no-text-decoration" %>
            <div id="comment-post-<%= post.id.to_s %>">
              <%= render 'comment_list', { post: post } %>
            </div>
            <%= link_to time_ago_in_words(post.created_at).upcase + "前", post_path(post),
              class: "light-color post-time no-text-decoration" %>
            <hr>
            <div class="row actions" id="comment-form-post-<%= post.id.to_s %>">
              <%= form_with model: [post, Comment.new], class: "w-100" do |f| %>
                <%= f.hidden_field :user_id, value: current_user.id %>
                <%= f.hidden_field :post_id, value: post.id %>
                <%= f.text_field :comment, class: "form-control comment-input border-0", placeholder: "コメント ...", autocomplete: :off %>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/posts/index.html.haml
- @posts.each do |post|
  .col-md-8.col-md-2.mx-auto
    .card-wrap
      .card
        .card-header.align-items-center.d-flex
          -# = link_to user_path(post.user), class: "no-text-decoration" do
          -#   = image_tag avatar_url(post.user), class: "post-profile-icon"
          %table.table
            %thead.tableHead
              %tr.theadLine
                %th.title
                  = link_to post.title, post_path(post), class: "postTitle"
                %th.author
                  = link_to user_path(post.user), class: "black-color no-text-decoration", title: post.user.name do
                    %strong= post.user.name
            %tbody
              %tr.secondRecord
                %td.secondRecord__category
                  %p= simple_format(post.caption.truncate(70, omission: '...')) 
                %td.secondRecord__category
                  %span= post.created_at

              %tr.secondRecord
                %td.secondRecord__category
                  %div{:id => "like-icon-post-#{post.id.to_s}"}
                    - if post.liked_by(current_user).present?
                      = link_to "いいねを取り消す", post_like_path(post.id, post.liked_by(current_user)), method: :DELETE, remote: true, class: "loved hide-text"
                    - else
                      = link_to "いいね", post_likes_path(post), method: :POST, remote: true, class: "love hide-text"
          -# - if post.user_id == current_user.id
          -#   = link_to post_path(post), method: :delete, class: "ml-auto mx-0 my-auto" do
          -#     .delete-post-icon
          -# = link_to(edit_post_path(post)) do
          -#   編集
        -# .card-body
        -#   .row.parts
            -# %div{:id => "like-text-post-#{post.id.to_s}"}
            -#   = render "like_text", { likes: post.likes }
            -# %div
            -#   %br
            -#   %br
              -# %div{:id => "comment-post-#{post.id.to_s}"}
              -#   = render 'comment_list', { post: post }
            -# = link_to "", "#", class: "comment"
            -# %hr/
            -# .row.actions{:id => "comment-form-post-#{post.id.to_s}"}
            -#   = form_with model: [post, Comment.new], class: "w-100" do |f|
            -#     = f.hidden_field :user_id, value: current_user.id
            -#     = f.hidden_field :post_id, value: post.id
            -#     = f.text_field :comment, class: "form-control comment-input border-0", placeholder: "コメント ...", autocomplete: :off

app/views/posts/show.html.erb
<div class="col-md-10 col-md-offset-1 mx-auto postShow-wrap">
  <div class="row post-wrap">
    <div class="col-md-8">
      <div class="card-left">
        <%# <%= image_tag @post.photos.first.image.url(:medium), class: "card-img-top" %> 
      </div>
    </div>
    <div class="col-md-4">
      <div class="card-right">
        <div class="card-right-comment">
          <div class="card-right-name">
            <%= link_to user_path(@post.user), class: "no-text-decoration" do %>
              <%= image_tag avatar_url(@post.user), class: "post-profile-icon" %>
            <% end %>
            <%= link_to user_path(@post.user), class: "black-color no-text-decoration post-user-name",
              title: @post.user.name do %>
              <strong><%= @post.user.name %></strong>
            <% end %>
            <% if @post.user_id == current_user.id %>
              <%= link_to post_path(@post), method: :delete, class: "ml-auto mx-0 my-auto" do %>
                <div class="delete-post-icon">
                </div>
              <% end %>
              <%= link_to(edit_post_path(@post)) do %>
                編集
              <% end %>
            <% end %>
          </div>
          <div class="m-2">
            <strong>
              <%= @post.caption %>
            </strong>
          </div>
          <div class="comment-post-id">
            <div class="m-2">

              <div id="comment-post-<%= @post.id.to_s %>">
                <%= render 'comment_list', post: @post %>
              </div>


            </div>
            <div class="m-2">
              <div id="page-post-<%= @post.id.to_s %>">
                <%= render 'page_list', post: @post %>
              </div>
            </div>
          </div>
        </div>
        <div class="row parts">

          <div id="like-icon-post-<%= @post.id.to_s %>">
            <% if @post.liked_by(current_user).present? %>
              <%= link_to "いいねを取り消す", post_like_path(@post.id, @post.liked_by(current_user)), method: :DELETE, remote: true, class: "loved hide-text" %>
            <% else %>
              <%= link_to "いいね", post_likes_path(@post), method: :POST, remote: true, class: "love hide-text" %>
            <% end %>
          </div>
        </div>

        <div id="like-text-post-<%= @post.id.to_s %>">
          <%= render "like_text", { likes: @post.likes } %>
        </div>

        <div class="post-time"><%= time_ago_in_words(@post.created_at).upcase %>前</div>
        <hr>
          <div class="row parts" id="comment-form-post-<%= @post.id.to_s %>">
          <%= form_with model: [@post, Comment.new],  class: "w-100" do |f| %>
            <%= f.hidden_field :user_id, value: current_user.id %>
            <%= f.hidden_field :post_id, value: @post.id %>
            <%= f.text_field :comment, class: "form-control comment-input border-0", placeholder: "コメント ...", autocomplete: :off %>
          <% end %>
        </div>



        <div class="row parts" id="page-form-post-<%= @post.id.to_s %>">
          <%= form_with model: [@post, Page.new],  class: "w-100" do |f| %>
            <%= f.hidden_field :user_id, value: current_user.id %>
            <%= f.hidden_field :post_id, value: @post.id %>
            <%= f.text_field :body, class: "form-control comment-input border-0", placeholder: "投稿 ...", autocomplete: :off %>
          <% end %>
        </div>

      </div>
    </div>
  </div>
</div>

app/views/posts/show.html.haml
.col-md-10.col-md-offset-1.mx-auto.postShow-wrap
  .row.post-wrap
    -# .col-md-0
    -#   .card-left
    .col-md-10.center
      .card-right
        -# ここは作者用メニューです
      .card-body
        -# 新しい話を追加する
        -# .row.parts{:id => "page-form-post-#{@post.id.to_s}"}
        -#   = form_with model:[@post, Page.new], class: "upload-images p-0 border-0" do |f|
        -#     = f.hidden_field :user_id, value: current_user.id
        -#     = f.hidden_field :post_id, value: @post.id
        -#     = f.text_field :title  ,class: "form-control", placeholder: "タイトル", autocomplete: :on
        -#     = f.text_area :body, placeholder: "本文" , rows: "10", class: "form-control", autocomplete: :on

        -#     = f.submit "投稿する", class: "btn btn-primary"
        -#     %hr
        .card-right-comment
          .card-right__first
            = link_to user_path(@post.user), class: "no-text-decoration" do
              -# = image_tag avatar_url(@post.user), class: "post-profile-icon"
            %strong.postShowTitle
              = @post.title
          .card-right__second
            = link_to user_path(@post.user), class: "black-color no-text-decoration post-user-name", title: @post.user.name do
              作者: 
              %strong= @post.user.name
          -#   - if @post.user_id == current_user.id
          -#     = link_to post_path(@post), method: :delete, class: "ml-auto mx-0 my-auto" do
          -#       .delete-post-icon
          -#     = link_to(edit_post_path(@post)) do
          -#       編集
          -# .m-2
          %br
            %p.caption= safe_join(@post.caption.split("\n"), tag(:br))
            %hr
            %div{:id => "page-post-#{@post.id.to_s}"}
              = render 'page_list', post: @post
        .row.parts
          %div{:id => "like-icon-post-#{@post.id.to_s}"}
            - if @post.liked_by(current_user).present?
              = link_to "いいねを取り消す", post_like_path(@post.id, @post.liked_by(current_user)), method: :DELETE, remote: true, class: "loved hide-text"
            - else
              = link_to "いいね", post_likes_path(@post), method: :POST, remote: true, class: "love hide-text"
        %div{:id => "like-text-post-#{@post.id.to_s}"}
          = render "like_text", { likes: @post.likes }
        .post-time
          = time_ago_in_words(@post.created_at).upcase
          前
        -# %hr/
        .row.parts{:id => "comment-form-post-#{@post.id.to_s}"}
          = form_with model: [@post, Comment.new],  class: "w-100" do |f|
            = f.hidden_field :user_id, value: current_user.id
            = f.hidden_field :post_id, value: @post.id
            = f.text_field :comment, class: "form-control comment-input border-0", placeholder: "コメント ...", autocomplete: :off
          .comment-post-id
            .m-2
              %div{:id => "comment-post-#{@post.id.to_s}"}
                = render 'comment_list', post: @post
        -# .row.parts{:id => "page-form-post-#{@post.id.to_s}"}
        -#   = form_with model: [@post, Page.new],  class: "w-100" do |f|
        -#     = f.hidden_field :user_id, value: current_user.id
        -#     = f.hidden_field :post_id, value: @post.id
        -#     = f.text_field :title, placeholder: "タイトル ...", autocomplete: :off
        -#     = f.text_field :body, placeholder: "投稿 ...", autocomplete: :off
        -#     = f.submit "投稿する", class: "btn btn-primary"